import { describe, expect, it } from "vitest";
import {
  conditionHighlights,
  conditionItems,
  conditionsUserMsg,
  developmentContribution,
  isGrounded,
  parseHighlights,
  payableAmounts,
} from "../../api/_conditions/highlights.mjs";

/** Real conditions from DLR D26A/0070/WEB, the case that prompted this. */
const DLR = [
  { code: "C", order: 1, title: "C1", text: "1. The development shall be carried out in its entirety in accordance with the plans, particulars and specifications lodged with the application.\nREASON: To ensure that the development shall be in accordance with the permission." },
  { code: "C", order: 4, title: "C4", text: "4. The disposal of surface water shall be in accordance with the requirements of the Planning Authority as follows:\n(a) The surface water runoff generated by the extension shall not be discharged to the public sewer but shall be infiltrated locally to a soakaway.\n(c) A minimum of one third of the front garden area shall remain as grass.\nREASON: In the interest of public health." },
  { code: "C", order: 5, title: "C5", text: "5. (a) The width of the proposed widened vehicular entrance shall be a maximum of 3.5m.\nREASON: In the interest of orderly development." },
  { code: "N", order: 0, title: "NOTES", text: "NOTE 1: The attention of the applicant is drawn to Section 34(13)." },
  { code: "R", order: 0, title: "FS", text: "First Schedule\nReasons And Considerations" },
];

describe("conditionItems", () => {
  it("reads only the conditions, not the notes or the first schedule", () => {
    expect(conditionItems(DLR).map((c) => c.title)).toEqual(["C1", "C4", "C5"]);
  });
  it("drops an empty condition rather than sending the model a blank", () => {
    expect(conditionItems([{ code: "C", order: 1, text: "   " }])).toHaveLength(0);
  });
  it("survives a decision with no items at all", () => {
    expect(conditionItems(undefined)).toEqual([]);
    expect(conditionItems([])).toEqual([]);
  });
});

describe("conditionsUserMsg", () => {
  it("labels each condition with the number the reader sees", () => {
    const msg = conditionsUserMsg(conditionItems(DLR));
    expect(msg).toContain("--- Condition 1 ---");
    expect(msg).toContain("--- Condition 5 ---");
    // Numbering must follow item.order, not position, or a highlight would
    // link to the wrong condition.
    expect(msg).not.toContain("--- Condition 2 ---");
  });

  it("sends the stock-looking conditions too — the specifics hide inside them", () => {
    // The grass rule lives inside a surface-water condition; filtering stock
    // themes out before the model would lose it.
    expect(conditionsUserMsg(conditionItems(DLR))).toContain("one third of the front garden");
  });
});

describe("isGrounded", () => {
  const cond = "The width of the proposed widened vehicular entrance shall be a maximum of 3.5m.";

  it("accepts a figure that really is in the condition", () => {
    expect(isGrounded("The widened entrance can be no more than 3.5 m wide.", cond)).toBe(true);
  });

  it("rejects a figure the condition never states", () => {
    // The failure that matters: someone designs to a 4.5 m entrance the
    // council did not permit.
    expect(isGrounded("The widened entrance can be no more than 4.5 m wide.", cond)).toBe(false);
  });

  it("passes a point that quotes no figure at all", () => {
    expect(isGrounded("A third of the front garden must stay as grass.", cond)).toBe(true);
  });

  it("matches money across the thousands separator", () => {
    const money = "shall pay the sum of €4,328.38 to the Planning Authority";
    expect(isGrounded("You must pay €4,328 before starting.", money)).toBe(true);
    expect(isGrounded("You must pay €5,328 before starting.", money)).toBe(false);
  });

  it("checks every figure, not just the first", () => {
    const c = "boundary walls limited to 0.9m and pillars to 1.2m";
    expect(isGrounded("Walls max 0.9m, pillars max 1.2m.", c)).toBe(true);
    expect(isGrounded("Walls max 0.9m, pillars max 2.4m.", c)).toBe(false);
  });
});

describe("parseHighlights", () => {
  const items = conditionItems(DLR);
  const ok = (h: unknown) => JSON.stringify({ highlights: h });

  it("reads the model's JSON", () => {
    const out = parseHighlights(
      ok([{ n: 5, point: "The widened entrance can be at most 3.5m wide." }]),
      items
    );
    expect(out).toEqual([{ n: 5, point: "The widened entrance can be at most 3.5m wide." }]);
  });

  it("unwraps a fenced or prefaced reply", () => {
    const raw = "Here you go:\n```json\n" + ok([{ n: 4, point: "Keep a third of the front garden as grass." }]) + "\n```";
    expect(parseHighlights(raw, items)).toHaveLength(1);
  });

  it("drops a condition number the decision does not have", () => {
    // An invented condition would link the reader to nothing.
    expect(parseHighlights(ok([{ n: 9, point: "Something the council never said." }]), items)).toEqual([]);
  });

  it("drops a point whose figure is not in the condition it cites", () => {
    expect(
      parseHighlights(ok([{ n: 5, point: "The entrance can be up to 6m wide." }]), items)
    ).toEqual([]);
  });

  it("keeps the grounded point when an ungrounded one sits beside it", () => {
    const out = parseHighlights(
      ok([
        { n: 5, point: "Entrance capped at 9.9m." },
        { n: 4, point: "A third of the front garden must stay as grass." },
      ]),
      items
    );
    expect(out).toEqual([{ n: 4, point: "A third of the front garden must stay as grass." }]);
  });

  it("de-duplicates repeated condition numbers", () => {
    const out = parseHighlights(
      ok([
        { n: 5, point: "Entrance max 3.5m." },
        { n: 5, point: "Entrance width is limited." },
      ]),
      items
    );
    expect(out).toHaveLength(1);
  });

  it("caps the list so the block stays scannable", () => {
    const many = Array.from({ length: 12 }, () => ({ n: 4, point: "x".repeat(20) }));
    expect((parseHighlights(ok(many), items) ?? []).length).toBeLessThanOrEqual(6);
  });

  it("returns an empty list — a real answer — when nothing is notable", () => {
    expect(parseHighlights(ok([]), items)).toEqual([]);
  });

  it("returns null, not an empty list, when the model gave nothing usable", () => {
    // "Couldn't read them" must not render as "nothing here binds you".
    expect(parseHighlights(null, items)).toBeNull();
    expect(parseHighlights("I'm sorry, I can't help with that.", items)).toBeNull();
    expect(parseHighlights("{not json at all", items)).toBeNull();
    expect(parseHighlights('{"highlights":"nope"}', items)).toBeNull();
  });

  it("rejects a point too short to say anything or too long to read", () => {
    expect(parseHighlights(ok([{ n: 4, point: "ok" }]), items)).toEqual([]);
    expect(parseHighlights(ok([{ n: 4, point: "x".repeat(400) }]), items)).toEqual([]);
  });
});

describe("developmentContribution", () => {
  // Every fixture below is real register wording.
  const dlr = [
    { code: "C", order: 6, text: "Countywide Surface Water\n6. The Developer shall, prior to commencement, pay the sum of €51.60 to the Planning Authority as a contribution towards expenditure." },
    { code: "C", order: 7, text: "Countywide Transport Infrastructure\n7. The Developer shall pay the sum of €773.14 to the Planning Authority as a contribution towards expenditure." },
    { code: "C", order: 8, text: "Countywide Community & Parks\n8. The Developer shall pay the sum of €4,328.38 to the Planning Authority as a contribution towards expenditure." },
  ];

  it("totals the parts councils split it across (DLR D26A/0070/WEB)", () => {
    expect(developmentContribution(dlr)).toEqual({ total: 5153.12, condition: 6 });
  });

  it("cites the first contribution condition, so the link lands somewhere real", () => {
    expect(developmentContribution(dlr)?.condition).toBe(6);
  });

  it("sums several clauses inside one lumped condition (DLR D23B/0599)", () => {
    // Some DLR records arrive with every condition concatenated into one item;
    // one figure per condition charged €4.97 against a real bill of €497.15.
    const lumped = [
      {
        code: "C",
        order: 1,
        text:
          "4. The Developer shall pay the sum of €4.97 as a contribution towards expenditure. REASON: public health. " +
          "5. The Developer shall pay the sum of €74.58 as a contribution towards expenditure. REASON: orderly development. " +
          "6. The Developer shall pay the sum of €417.60 as a contribution towards expenditure.",
      },
    ];
    expect(developmentContribution(lumped)?.total).toBeCloseTo(497.15, 2);
  });

  it("takes the amended figure, not the superseded one (SD26A/0084W)", () => {
    // Charging the original here would overstate the bill by €133,742.88.
    const amended = [
      {
        code: "C",
        order: 18,
        text:
          "Financial Contribution. The developer shall pay a financial contribution of €222,068.16 in respect of public infrastructure. REASON: reasonable. " +
          "Condition 18 was amended by PR/0805/26 on 17/07/2026: Financial Contribution. The developer shall pay a financial contribution of €88,325.28 in respect of public infrastructure.",
      },
    ];
    expect(developmentContribution(amended)).toEqual({ total: 88325.28, condition: 18 });
  });

  it("ignores a passing reference to the contribution scheme with no figure", () => {
    expect(
      developmentContribution([
        { code: "C", order: 1, text: "…in accordance with the Development Contribution Scheme 2023-2028 made by the Council." },
      ])
    ).toBeNull();
  });

  it("is null when the council asked for no money", () => {
    expect(developmentContribution([{ code: "C", order: 1, text: "Build per the plans." }])).toBeNull();
  });

  it("reads cents and thousands separators the registers actually use", () => {
    expect(payableAmounts("pay the sum of €76,383 to the Authority")).toEqual([76383]);
    expect(payableAmounts("a financial contribution of €28.92 (twenty eight euros)")).toEqual([28.92]);
    expect(payableAmounts("no money here")).toEqual([]);
  });
});

describe("conditionHighlights", () => {
  it("does not call the model when the council imposed no conditions", async () => {
    let called = false;
    const out = await conditionHighlights([{ code: "N", order: 0, text: "note" }], async () => {
      called = true;
      return "{}";
    });
    expect(called).toBe(false);
    expect(out).toBeNull();
  });

  it("sends only the conditions and returns the validated points", async () => {
    let seen = "";
    const out = await conditionHighlights(DLR, async (_system: string, content: string) => {
      seen = content;
      return JSON.stringify({
        highlights: [
          { n: 5, point: "The widened entrance can be at most 3.5m wide." },
          { n: 1, point: "Build exactly what was on the lodged plans." },
        ],
      });
    });
    expect(seen).not.toContain("NOTE 1");
    expect(out).toHaveLength(2);
    expect(out?.[0].n).toBe(5);
  });

  it("passes a model failure through as null", async () => {
    expect(await conditionHighlights(DLR, async () => null)).toBeNull();
  });

  it("appends the money point last, so it never crowds out a design constraint", async () => {
    const items = [
      ...DLR,
      { code: "C", order: 6, title: "C6", text: "6. The Developer shall pay the sum of €51.60 as a contribution towards expenditure." },
    ];
    const out = await conditionHighlights(items, async () =>
      JSON.stringify({ highlights: [{ n: 5, point: "Entrance capped at 3.5m." }] })
    );
    expect(out).toEqual([
      { n: 5, point: "Entrance capped at 3.5m." },
      { n: 6, point: "€51.60 in development contributions is payable before work starts." },
    ]);
  });

  it("replaces a model point that duplicates the money condition", async () => {
    const items = [
      ...DLR,
      { code: "C", order: 6, title: "C6", text: "6. The Developer shall pay the sum of €51.60 as a contribution towards expenditure." },
    ];
    const out = await conditionHighlights(items, async () =>
      JSON.stringify({ highlights: [{ n: 6, point: "Pay €51.60 before starting." }] })
    );
    expect(out).toHaveLength(1);
    expect(out?.[0].point).toContain("development contributions");
  });
});
